# Generated by Django 2.2.6 on 2019-10-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0002_auto_20191016_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/product_photo'),
        ),
    ]
