# Generated by Django 2.2.6 on 2019-10-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0003_auto_20191017_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_photo'),
        ),
    ]
